workflows:
  ios-build:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.fanla.app"
    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Firebase modulemap fix
        script: |
          # firebase_messaging non-modular header hatasını önlemek için modulemap ekle
          MODULE_MAP="module Firebase {\n  umbrella header \"Firebase.h\"\n  export *\n  module * { export * }\n}"
          echo -e "$MODULE_MAP" > ios/Pods/Headers/Public/Firebase/Firebase.modulemap || true
      - name: Build iOS (release, no codesign)
        script: |
          flutter build ios --release --no-codesign --dart-define=BUNDLE_ID=$BUNDLE_ID
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - mustafa@example.com
